Wk fetcher api
Bible-Translation-Tools/Fetcher pull request #205
Opened 2024-06-04 18:53 UTC by wkelly17

Based on recent discussions around audio biel, I've taken the small api Max rolled for processing files on the cdn and moving them through AZ. Service bus. Max can clear up, but based on looking at it, there's a few observations here. 

1. It doesn't not duplicate fetcher pipeline.  It's not intended to recreate files on the cdn and reprocess everything in the event of a schema change or something. This merely reads the content path of the audio files, and will send a set of messages which the public data api schema could consume for audio projects.   That could be added later if needed, but I don't think it will.  The pipeling logic itself (the cron)  that generates those files on fetcher-pipeline is actually what would make those edits likelly. 
2. There does seem to be a route for consuming those messages over http instead of connecting directly to the bus if someone wanted to look at them but not have to connect the Azure SB. 
3. @danparisd  -> I stuck a super basic dockerFile in here and a makefile. The makefile is incomplete, but. I think that basic dockerfile shoudl be sufficient for running it next to the cdn.   The env vars at the top of main.py should be enough to run it.  it shouldn't really need any horsepower or memory much to run next to it. 

Anything to add @mXaln ? Or questions @PurpleGuitar  & @danparisd ?

2024-06-05 10:57 UTC, mXaln requested changes

2024-06-05 10:57 UTC, mXaln commented on fetcher-pipeline-api/app/generate_content.py
I would totally delete this file. I created it for testing purpose that created dummy content. It could be dangerous on the server, 'cause once it runs it will replace all real content with dummy one.

2024-06-05 10:57 UTC, mXaln commented on fetcher-pipeline-api/app/main.py
> +@app.get("/receive_messages")
I would also remove this function. It meant to be created for tests. It not only gets messages from the service buss but also consumes them, so they are not anymore available for other functions.

2024-06-05 11:47 UTC, mXaln commented on fetcher-pipeline-api/app/main.py
> +        print(len(chunks))
I forgot to remove `print` here

2024-06-05 11:56 UTC, mXaln commented on fetcher-pipeline-api/app/main.py
> +                await sender.send_messages(batch_message)
This should be indented one level up to run after `for`loop, not in the loop. My bad.

2024-06-06 13:37 UTC, mXaln submitted a review, later dismissed

2024-06-06 18:17 UTC, wkelly17 reviewed
@danparisd  -> adjusted the devops files to make use of the dockerfile I had written. Looking at it though, looks like I forgot to expose whatever port fastapi runs on and map it in the compose. I think the default is 80, but looks like that's taken by the fileserver

2024-06-26 20:37 UTC, wkelly17 commented
Closing in favor of https://github.com/WycliffeAssociates/Fetcher_utils, which is deployed for local dev assist.

2024-06-26 20:37 UTC, closed without merging